### ISSUE TITLE
Support the entire FARUM API

### ISSUE THREAD

**Issue by kalnun** [coinmetrics/api-client-python#2]
It would be awesome if you could add support for the Timeseries Futures data endpoint.

**Comment by oleksandr-cm** [comment]
Thank you for this request, we will prioritize support of those endpoints and will post updates here when it is available

**Comment by oleksandr-cm** [comment]
the endpoint was added to the client
https://coinmetrics-io.github.io/api-client-python/site/api_client.html#get_mining_pool_tips_summary

please let us know if you face any issues or have any other requests
