### ISSUE TITLE
Python API client website is down

### ISSUE THREAD

**Issue by victoreram** [coinmetrics/api-client-python#3]
The [Python API client website](https://coinmetrics.github.io/api-client-python/) is down. Getting a 404
![Screen Shot 2021-09-15 at 12 34 22 PM](https://user-images.githubusercontent.com/20134007/133482027-be2a7ef0-f4e4-4dcb-b6f1-5f781d4ba06b.png)

**Comment by ahcub** [comment]
The link to the docs is incorrect for some reason
Here is the correct link
https://coinmetrics.github.io/api-client-python/docs/

**Comment by victoreram** [comment]
False alarm; site is found here: https://coinmetrics.github.io/api-client-python/site/
