### ISSUE TITLE
[Question] How do you handle too many requests errors?

### ISSUE THREAD

**Issue by gat786** [coinmetrics/api-client-python#6]
I am trying to fetch a lot of data using the API and I have curious about how to handle too many requests error once I face them. I see no mentions of how to tackle them in the docs as well. 

Would be great if something can be made to tackle that.

**Comment by ianmclaughlin-cm** [comment]
Hi,

Sorry that I didn't get back you earlier on this issue. Could you share the script you are using to access the data along with the error iteslf? There is rate limits associated with the community API so the best option may be to loop your requests with sleep times in between in order to stay below the limits of the community API, but happy to help more if I can

**Comment by gat786** [comment]
I have managed to somehow handle it for right now. But the problem that I was facing was due to me not being get the window size or the requests remaining headers from the requests as the client itself only provides data and no way to get headers.

**Comment by gat786** [comment]
I am in a situation where in sometimes I use the community api and sometimes the premium ones. Both of which have different window sizes. So to exactly get the next window time it is essential to know the size of window i.e. either 20 seconds or 10 minutes. It would be great if gaining those details can be somehow added to the client.

**Comment by ianmclaughlin-cm** [comment]
I see, so the best way to figure out what is available from the community api is to use the `catalog` endpoints.  So, assuming you are talking about asset-pair-candles, if you wanted to figure out what frequencies are available for each candles you might run a script such as:
```python
import pprint
from coinmetrics.api_client import CoinMetricsClient

if __name__ == "__main__":
    client = CoinMetricsClient()
    all_asset_pairs = client.catalog_asset_pair_candles()
    pprint.pprint(all_asset_pairs, indent=4)```

which prints a reponse:
```
[   {   'frequencies': [   {   'frequency': '1h',
                               'max_time': '2022-08-23T14:00:00.000000000Z',
                               'min_time': '2020-12-26T01:00:00.000000000Z'},
                           {   'frequency': '1d',
                               'max_time': '2022-08-22T00:00:00.000000000Z',
                               'min_time': '2020-12-26T00:00:00.000000000Z'}],
        'pair': '1inch-usd'},
    {   'frequencies': [   {   'frequency': '1h',
                               'max_time': '2022-08-23T14:00:00.000000000Z',
                               'min_time': '2020-10-10T08:00:00.000000000Z'},
                           {   'frequency': '1d',
                               'max_time': '2022-08-22T00:00:00.000000000Z',
                               'min_time': '2020-10-10T00:00:00.000000000Z'}],
        'pair': 'aave-usd'},
....
```

The [documentation for that feature is here](https://docs.coinmetrics.io/api/v4#tag/Catalog). We are always looking to making the API client easier to use for both community and pro users and making it clear what data we offer. Is this example clear? Is there any feedback you have that could make this easier for your use case?

One idea I had was adding a CLI feature that allows users to quickly check API permissions, something like `coinmetrics catalog asset-pair-candles` that prints in the terminal what is available maybe, but we are exploring a few options so any feedback would be helpful.

**Comment by gat786** [comment]
By window size I meant the sliding window that CoinMetrics uses to limit the requests.

**Comment by ianmclaughlin-cm** [comment]
Sorry could you clarify with an example, ideally either a python code example or http request snippet? I'm not sure what you mean by sliding window in this case.
