### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fabaff** [coinmetrics/api-client-python#8]
The latest release seems to be different on different "release channels":

- `master` says [2022.07.21.10](https://github.com/coinmetrics/api-client-python/blob/master/pyproject.toml#L3)
- PyPi has [2022.8.12.7](https://pypi.org/project/coinmetrics-api-client/2022.8.12.7/)
- GitHub release (latest tag): [2021.09.27.16.20](https://github.com/coinmetrics/api-client-python/releases/tag/2021.09.27.16.20) 

It would be very helpful if you could tag releases. This would enable distributions who want to fetch the source from GitHub instead of PyPI.

Thanks

**Comment by ianmclaughlin-cm** [comment]
Thanks for raising this issue, the correct version is the PyPi one. I will fix that now and change our pipeline to do that automatically ideally. As for the Git tagging, we will aim to include that in future releases as well. Your feedback is really appreciated!
